FROM kalilinux/kali-rolling
LABEL org.opencontainers.image.authors="githubfoam"


RUN set -xe && \
    export DEBIAN_FRONTEND=noninteractive && \
    apt-get -qq update && \
    apt-get -qqy upgrade

RUN set -xe && \
    apt-get install zenmap nmap etherape -y

